[general]
import = ["~/.config/alacritty/themes/lugh_evolve.toml"]
[env]
TERM = "xterm-256color"
[window]
decorations = "None"
dynamic_padding = true
[font]
normal = { family = "Inconsolata Nerd Font", style="Regular" }
size = 13
[cursor]
style = { shape = "Block", blinking = "Never" }
[mouse]
hide_when_typing = true
[keyboard]
bindings = [
  { key = "Q", mods = "Control", action = "Quit" },
]
