# Personnal Password Store
# Lucas Hadey
# Aka Lug, ARTSYS, Aethros

[DevOp.Github]
password = 'sh&jE~*w2lYH\*X'
email = "lhflyextra300@gmail.com"

[DevOp.o2switch]
password = '$Syste;+98'
username = "artsys"

[DevOp.Docker]
password = 'eH8]AQ4BGcLs]E4'
email = "hadeylucaspro@gmail.com"

[Media.Appletv]
password = 'Toulon19638321'
email = "thierry.hadey@gmail.com"

[Media.Deezer]
password = 'Whisky21!'
email = "ldescot@gmail.com"

[Media.Netflix]
password = 'loulou2019'
email = "hadey.thierry@gmail.com"

[Media.Twitch]
password = '/Qf3Yp:N{)tfGuS'
username = "artsys"

[Social.Komoot]
password = '>Hp@vBDLl\!oGvd'
email = "lhflyextra300@gmail.com"

[Social.Twitter]
password = 'sZG{n?k_)Xj(s4Y'
email = "lhflyextra300@gmail.com"

[Social.Letterboxd]
passwword = '&veRjS}]YA+q:,R'
username = "Mr_Artsys"

[Other.CodinGame]
password = 'FT&\OAR/B6uR]/k'
email = "hadeylucaspro@gmail.com"

[Other.Google]
password = 'FYy&VL#`J,/BChV'
email = "lhflyextra300@gmail.com"

[Other.MFC]
password = 'C1&G_uFLW%^THU6'
email = "hadeylucaspro@gmail.com"

[Other.Mozilla]
password = '|79~R}R7l!}bT9%'
email = "lhflyextra300@gmail.com"

[Other.SNCF]
password = "53[{FzHD'D]@HYQ"
email = "lhflyextra300@gmail.com"
